---
- hosts: tomcat1
  remote_user: ec2-user
  become: yes
  tasks:
      - name : deploying war file
        copy : src=/home/raju/deployartifacts/myweb.war dest=/usr/share/tomcat/webapps/myweb.war

      - name : restart the service
        service : name=tomcat   state=restarted
